apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-replicaset
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: node-app
  template:
    metadata:
       labels:
         app: node-app
    spec: 
      containers:
        - name: node-container
          image: cloudservos2607/node-image:latest

